### ISSUE TITLE
Error Attempting to Start PathWeaver

### ISSUE THREAD

**Issue by vikings4276** [wpilibsuite/PathWeaver#109]
Hello,
I get an error when attempting to start PathWeaver  (in windows cmd prompt, when I execute "gradlew run").  I get a Java compiling exception which starts with the following:

> Task :compileJava
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\CreateProjectController.java:69: error: cannot infer type arguments for StringConverter<T>
    game.converterProperty().setValue(new StringConverter<>() {
                                                         ^
  reason: cannot use '<>' with anonymous inner classes
  where T is a type-variable:
    T extends Object declared in class StringConverter
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\Waypoint.java:117: error: cannot find symbol
          .setContent(Map.of(DataFormats.WAYPOINT, "point"));
                         ^
  symbol:   method of(DataFormat,String)
  location: interface Map
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\Waypoint.java:122: error: cannot find symbol
          .setContent(Map.of(DataFormats.CONTROL_VECTOR, "vector"));
                         ^
  symbol:   method of(DataFormat,String)
  location: interface Map
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\EditWaypointController.java:37: error: cannot find symbol
    controls = List.of(xPosition, yPosition, tangentX, tangentY, lockedTangent, pointName);
                   ^
  symbol:   method of(TextField,TextField,TextField,TextField,CheckBox,TextField)
  location: interface List
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\EditWaypointController.java:39: error: cannot find symbol
    textFields = List.of(xPosition, yPosition, tangentX, tangentY);
                     ^
  symbol:   method of(TextField,TextField,TextField,TextField)
  location: interface List
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\EditWaypointController.java:126: error: cannot find symbol
    List.of(xPosition, yPosition, tangentX, tangentY, pointName)
        ^
  symbol:   method of(TextField,TextField,TextField,TextField,TextField)
  location: interface List
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\FxUtils.java:33: error: cannot find symbol
    SUBCHILD_SELECTORS = List.of(selectors);
                             ^
  symbol:   method of(PseudoClass[])
  location: interface List
C:\Users\ericg\Desktop\PathWeaver-master\src\main\java\edu\wpi\first\pathweaver\MainController.java:218: error: cannot infer type arguments for ChangeListener<T>
        new ChangeListener<>() {
                          ^
  reason: cannot use '<>' with anonymous inner classes

Longer dump is here:
https://docs.google.com/document/d/1izP3UGHHRQxdNcUC1U56ZWblweYVJMsYWOcdPILYVXQ/edit?ts=5bcffa67

**Comment by ThadHouse** [comment]
What version of Java are you using? I think the build requires Java 11. That's all we test with currently.

**Comment by SamCarlberg** [comment]
Pathweaver requires Java 11 to compile and run; you appear to be using Java 8 or 9.

The Java 11 JDK can be downloaded [here](http://jdk.java.net/11/)
