### ISSUE TITLE
Edit values ​​in meter

### ISSUE THREAD

**Issue by nathanmutin** [wpilibsuite/PathWeaver#110]
Please think of none-us teams and allow them to edit robot constants (max velocity, ...) and waypoints in meters.

**Comment by gftabor** [comment]
Just thought you would appreciate some of the new PR here #115 .

Specifically this text 

> The field units are case-insensitive and can be in meters, cm, mm, inches, feet, yards, or miles. Singular, plural, and abbreviations are supported (eg "meter", "meters", and "m" are all valid for specifying meters)
