### ISSUE TITLE
Ability to add new fields

### ISSUE THREAD

**Issue by bid-p** [wpilibsuite/PathWeaver#112]
**Is your feature request related to a problem? Please describe.**  
I'd like the ability to add new fields.

**Additional context**  
@gftabor did include this in his now-closed issue: https://github.com/wpilibsuite/PathWeaver/issues/26
However, him saying "For creating new fields it should ask for an image and let a user drag the edges of rectangle to select an important region of the image. Then it should ask the user to enter real Length or Width of the field in any units they choose. The dimension they don't enter should be auto generated to match the ratio of the field image." seems to have been overlooked.

Thanks!

**Comment by kjrobrien** [comment]
See #115 for how to add the Turning Point field using the new game loader.
