### ISSUE TITLE
Can't see the field descriptions on the "Create Project" dialog

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/PathWeaver#117]
**Describe the bug**  

**To Reproduce**  
1. ...
2. ...

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version [e.g. 1.10.1]

**Additional context**

**Comment by bradamiller** [comment]
The text labels "Maximum jerk (acceleration per second)" and "Distance between left and right of wheel" is cut off in the dialog box and it can't be resized. The problem is that the cut off part is the units.

**Comment by kjrobrien** [comment]
This seems to only happen on Mac OS. I will look into it.

**Comment by SamCarlberg** [comment]
I see it on Linux, too

**Comment by kjrobrien** [comment]
Closed by #123
