### ISSUE TITLE
Save Button For Modified Paths

### ISSUE THREAD

**Issue by abbajabalroba** [wpilibsuite/PathWeaver#120]
@zengstellas Made this in my account by accident.

**Is your feature request related to a problem? Please describe.**  
There is no Save button in PathWeaver to save modifications.

**Describe the solution you'd like**  
Some sort of Save button, since the only other way is to get a prompt when clicking "Build Path."

**Describe alternatives you've considered**  
Currently we click off of the modified path, get a Save prompt, and save that way.

**Additional context**  
None

**Comment by gftabor** [comment]
Believe this was always handled in 
#87 
Someone can reopen if that is not the case.
