### ISSUE TITLE
Add Destination Deep Space Field

### ISSUE THREAD

**Issue by kjrobrien** [wpilibsuite/PathWeaver#129]
**Is your feature request related to a problem? Please describe.**  
The only included field with PathWeaver currently is the Power Up field. 

**Describe the solution you'd like**  
PathWeaver should include the Destination Deep Space image after the FRC kickoff on January 5th.

**Describe alternatives you've considered**  
A zip file can be uploaded with the field for teams to include just after kickoff. This would allow teams to use PathWeaver with the Destination Deep Space field before a new release of PathWeaver.

**Comment by auscompgeek** [comment]
Fixed by #131?

**Comment by kjrobrien** [comment]
Yes, forgot I made this issue. Thanks!
