### ISSUE TITLE
Centimeters and millimeters are not handled by the field image properly

### ISSUE THREAD

**Issue by Oran-Zafrani** [wpilibsuite/PathWeaver#133]
Hey,

The PathWeaver is not letting me draw a free path, it looks like the graph that represents the FIRST PowerUp Field is not fulling shown on the tool's window.  

I hope that you'll fix that soon.

Thanks!

**Comment by Oran-Zafrani** [comment]
![image](https://user-images.githubusercontent.com/33689701/51076000-a83fb480-169b-11e9-9a48-cee5d23addb9.png)

I'm using Windows 10 x64 bit with the 1920x1080 resolution, without text or dpi scaling.

**Comment by AustinShalit** [comment]
?"free path" מה זאת אומרת

**Comment by AustinShalit** [comment]
?אילו יחידות מדידה יש לך

**Comment by Oran-Zafrani** [comment]
> ?"free path" מה זאת אומרת

זה נראה כאילו הוא מתחיל ממקום שהוא לא נמצא בתוך הזירה שאני רואה פה לפחות, אמור להיות לו מקום מוצא ואני לא רואה את פה

**Comment by Oran-Zafrani** [comment]
> ?אילו יחידות מדידה יש לך

השתמשתי בסנטימטרים

**Comment by AustinShalit** [comment]
I tried this on my computer and it looks like centimeters are broken with the default path.

@Oran-Zafrani תודה רבה לך! אנחנו עובדים על זה. השתמש מטרים עכשיו.

**Comment by AustinShalit** [comment]
@Oran-Zafrani  בעיה זו תוקנה ב 2019.2.1. אנא בדוק.
