### ISSUE TITLE
Crash saving over locked CSV files

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/PathWeaver#135]
**Describe the bug**  
When a path CSV file is open/locked by Excel, building paths crashes PathWeaver with an error.

**To Reproduce**  
1. Create a path
1. Click **Build Paths**
1. Open one of the generated path CSV files in Excel
1. Click **Build Paths**
At this point PathWeaver will crash silently.

**Expected behavior**  
Since the file is locked it cannot be overwritten, but an error message should be displayed instead of crashing PathWeaver.

**Desktop**
 - OS: Windows 10
 - Java version: 11.0.1 (installed by WPILib)

**Comment by jasondaming** [comment]
I was unable to reproduce this issue.  Is anyone else able to reproduce this?

**Comment by agasser** [comment]
When this bug was written in 2019 Pathweaver exported a CSV file that could be opened directly in Excel. Now it exports a JSON file and most editors (e.g. VS Code) do not lock the file so this is much less likely to occur.

**Comment by jasondaming** [comment]
I tried opening the json with a variety of programs: vscode, excel, word, notepad etc and none crashed it so "hopefully" we are good!

**Comment by agasser** [comment]
I tried marking the output file read-only to see if PathWeaver would crash, and it did not. It displayed a message saying the path was exported even though it was not, but PathWeaver did not crash.
