### ISSUE TITLE
Left and Right paths are swapped

### ISSUE THREAD

**Issue by icemannie** [wpilibsuite/PathWeaver#137]
The attached files are from a path drawn from the left load station to the left of the cargo ship. See the images. The left and right csv files (couldn't attach) show the right traveling 32 ft and the left 28 ft although the left is on the outside of the path. Also the heading is positive although Pathfinder convention has it negative.

This and other paths don't run correctly on our test robot but equivalent Vannaka Motion Profile Generator generated paths do.
![left path](https://user-images.githubusercontent.com/19239226/51495163-f67e4300-1d80-11e9-9b65-d789a4515c67.PNG)
![right path](https://user-images.githubusercontent.com/19239226/51495164-f67e4300-1d80-11e9-9257-4b5a9a6a9288.PNG)

![angle2](https://user-images.githubusercontent.com/19239226/51494750-73a8b880-1d7f-11e9-918e-ca0369ab8bc3.PNG)
![point1](https://user-images.githubusercontent.com/19239226/51494852-d7cb7c80-1d7f-11e9-95fa-5c9f558eac12.PNG)
![point2](https://user-images.githubusercontent.com/19239226/51494853-d7cb7c80-1d7f-11e9-8bf2-55f4b529ce3e.PNG)

Windows laptop, V10, Java 11 Path Weaver 2019.2.1

**Additional context**

**Comment by SamCarlberg** [comment]
This is most likely just a problem with the pathfinder library. Can you try adding an intermediate waypoint to better define the path?

**Comment by kjrobrien** [comment]
Would you mind uploading your project or sharing the values of the points you are using so we can recreate this on our side? Thanks!

**Comment by icemannie** [comment]
[TempPW.zip](https://github.com/wpilibsuite/PathWeaver/files/2780662/TempPW.zip)
Zip folder of modified original path and second added test path

**Comment by icemannie** [comment]
Done. Let me know if more is needed.

**Comment by icemannie** [comment]
Great catch! Hadn’t noticed that but you are right. That brings up another question though. Why is the y origin at the top left of the Path Weaver image? Earlier programs have it bottom left. If the intention was for it to be at the bottom, right would be below left. 

One thing I like to do is an Excel XY scatter diagram to double check the path.  With the y origin at the top, it flips the curves.

My biggest question until today was the inverted heading from Pathfinder question.

I should say at this time, I really like some of the features of Pathweaver like path groups and the dragging the path.

John

**Comment by gftabor** [comment]
So in answer to your "why is it this way" question. The way we handle user units is (quite clever in my opinion) we make an pane that is the size of the field in your desired units, but drawn on top of the field image. So JavaFX is handling the conversion between drawn pixels, picture pixels and user feet for instance when drawing and devs don't have to think about it.

This means that if I ever made a waypoint print its location visually in PathWeaver it would all be in user desired units, that is the "native" units of everything you see drawn in path weaver other than the image. It saves a lot of bugs related converting back and forth between visual units and user units. 

It does have the consequence of (0,0) being in the upper left corner without constantly adjusting for it. Which honestly hadn't been a negative until this moment. 

I guess I never noticed because I have worked with images before and just kinda assumed that's where (0,0) was.
positive y being down (as is standard in images) vs positive y being up (as is standard everywhere else)


In lastly in terms of your point that this mixup between standards of positive vs negative y is the cause of left vs right being flipped. Ya your probably right. Needs to be investigated to see if flipping left/right back is always the correct answer(as I assume) or if changing our coordinate frame is necessary.

**Comment by icemannie** [comment]
https://www.chiefdelphi.com/t/pathfinder-coordinate-system/159870/7

John

**Comment by gftabor** [comment]
> https://www.chiefdelphi.com/t/pathfinder-coordinate-system/159870/7 John
> […](#)


Yup, the question is how to go about fixing the issue. We want to avoid breaking every path that anyone has made using pathWeaver. So minimum impact fixes are preferred. I believe just flipping left and right paths when we save them would be the only required change. (but needs someone to actually check) 
More drastic changes would change all the related path files and anyone with drawn paths now would have their paths magically move when they updated.

**Comment by icemannie** [comment]
First thing is to get it working correctly.  I would question whether swapping left and right is enough. The heading is incorrect also. I have attached csv's from an almost identical Moton Profile Generator Path showing a - heading. Heading is used in correcting the path of the robot so it needs to be right or the robot won't follow correctly.
 The only Chief Delphi post I have noticed on Path Weaver is from a team just learning trajectories.  If this isn't a real sshort term fix it would be better to let teams know.
Personally I would rather redo my trajectories and have the coordinate system standardised. We anticipate maybe 5 or 6 different one this year. Anyone doing more likely does their own path planning.
If you need any testing done, I would be happy to do that.

[LLDToCS_left.zip](https://github.com/wpilibsuite/PathWeaver/files/2781283/LLDToCS_left.zip)

**Comment by icemannie** [comment]
I was able to test simple left and right turns on the robot with the left side following the right path and vice versa and with heading negated.
Everything worked correctly.
I would be happy to test out the fix once you have it available.

**Comment by icemannie** [comment]
The college where we have our robot is closed today for weather conditions. It may be open this evening. 
I will build and look at the CSVs later this morning. I One change that you should - even must - make to help the change get accepted is to add a grid ruler to x and y axes on the image.  I simply made the assumption that y0 was bottom left and struggled with the paths not performing on the robot.

**Comment by icemannie** [comment]
Kevin,

Teams using Path Weaver need a fix now. A six week build season is short
enough.
I have posted on Chief Delphi accordingly.
Instead of rushing a release, why not get out a Team Update that explains
there is a problem, and how to get around it. If teams would still have to
make one change in code to invert heading, it would be straightforward
enough to have them either also read the left csv into the right Trajectory
and vice versa or read the left and right Trajectories into the right and
left Distance Followers.

Path Weaver can still be used for plotting the paths.

**Comment by bradamiller** [comment]
John - thanks for all your help testing and tracking down the problem. Seems like the right thing to do is let people know that the issue exists today so they can make the 2 line change to their code to work around the problem. Then we can fix it correctly in the next update with a clear description of the issue in the release notes.

**Comment by icemannie** [comment]
Brad, I agree wih that and will not test the version Kevin sent me. I posted on Chief Delphi this morning about the situation and so far at least not a single comment. That and no earlier questions seems to indicate low usage currently or teams aren't at that point yet. Perhaps the driver control in sandstorm autonomous is making teams less inclined to make the effort.
I have tested Vannaka Motion Profile Generator 4.0 and it works with standard equations.

**Comment by kjrobrien** [comment]
This decision has been reflected in the documentation on screensteps here:
https://wpilib.screenstepslive.com/s/currentCS/m/84338/l/1021631-integrating-path-following-into-a-robot-program and has been documented on the list of known issues here: https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/1028964-known-issues

**Comment by wrall** [comment]
I'm not sure that the solution of swapping left and right paths is universally the case.  I have some paths that work correctly and some that don't.  My paths basically always turn toward the left, even if they're supposed to turn towards the right.  A student made 5 paths (go straight, turn left, turn right, make clockwise circle, and drive a sine wave).  They all turn left (or go in a counter-clockwise circle).  Could there be a more fundamental problem?

**Comment by icemannie** [comment]
Did you invert the heading also? You need to.

**Comment by wrall** [comment]
The paths generated for the below have basically the same right and left position values, turning left.  The starting position for left and right are 0 inches, and the ending position for both paths are approximately 58" for left, 96" for right.
![image](https://user-images.githubusercontent.com/9663797/51796483-cda6e500-21a8-11e9-94f5-cc030b6c373f.png)

I could swap left and right for one of them, but it would be useful to know when that might happen without inspecting the paths too closely.

Also, for one of the paths I generated which was supposed to drive straight forwards 48", the last position values generated are only 46.5".

**Comment by wrall** [comment]
Smaller timestep does seem to allow it to reach the actual destination.  Very strange behavior.

[PathWeaver.zip](https://github.com/wpilibsuite/PathWeaver/files/2799791/PathWeaver.zip)

**Comment by wrall** [comment]
Ah, you're right - I assumed that the path was correct based on how it displayed, having not made them myself.

Some suggestions:
- Display a little number within each waypoint triangle identifying the order, or color-code them somehow.
- Change the Waypoint Properties pane to be in an ordered list format, with each row one showing all of those 5/6 (editable) columns.
- Provide the ability to add a new waypoint to the end of the path instead of having to create the first and last, then specify the middle.

**Comment by kjrobrien** [comment]
I like all of these ideas! I've opened an issue for a feature request #138.
