### ISSUE TITLE
Notify user when preferences file is corrupted

### ISSUE THREAD

**Issue by SpectrumFRC3847** [wpilibsuite/PathWeaver#142]
Image of the error. https://imgur.com/KDrWNwZ

When launching pathweaver from inside VScode, we get an exception in application start method. The program was working before and allowing us to generate paths but now when we attempt to launch it only comes up with this error screen. We have rerun the WPILib installer but that didn't fix the issue.

**Comment by kjrobrien** [comment]
Can you post the file C:\Users\<YourUsername>\PathWeaver\pathweaver.json the error suggests it may have been corrupted.

**Comment by SpectrumFRC3847** [comment]
Well when I try to open it, VScode can't so my guess is that it's very corrupted. Deleting let me launch pathweaver again, just lost my projects but I'm not that far in. 

Might be a good idea to move that file somewhere where it's easier to be source controlled.

**Comment by kjrobrien** [comment]
That file is computer specific. You should be able to re-import your existing projects.

**Comment by SpectrumFRC3847** [comment]
cool, that worked, okay thank you
