### ISSUE TITLE
Side Velocities exceed maximum

### ISSUE THREAD

**Issue by Diverjim84** [wpilibsuite/PathWeaver#145]
In a setup with the max V set to 6, and a path that does a 90 degree turn, the plot of the outside wheel velocity exceeds the 6 in/s value.  Plot attached,  Green is velocity, blue is acceleration, and red is position. 
![LeftTurn](https://user-images.githubusercontent.com/20145243/67061126-1f671500-f114-11e9-8862-402f06e8b2bb.png)

**Comment by sciencewhiz** [comment]
This is an issue with the pathfinder library used by pathweaver. https://github.com/JacisNonsense/Pathfinder/issues/14

**Comment by carbotaniuman** [comment]
The switch to WPILib splines by the 2020 season should alleviate this issue.

**Comment by AustinShalit** [comment]
WPILib 2020 will be released at (or slightly before) kickoff
