### ISSUE TITLE
Regression: Saving stuff is screwed up

### ISSUE THREAD

**Issue by carbotaniuman** [wpilibsuite/PathWeaver#150]
**Describe the bug**  
Saving paths and saving projects is broken.

**To Reproduce**  
Path issues:
1. Make a new path.
2. Make some changes.
3. Save it.
4. Reload the path.

Project issues:
1. Make a new project.
2. Exit the program.
3. Reopen the program and check the recent.

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java version: Rio JDK 11

**Additional context**  
Running on latest commit (merge of my PR).

**Comment by babbott1000** [comment]
![savePathBug](https://user-images.githubusercontent.com/20113527/68447257-ef57e280-01a4-11ea-93b0-4209c8e5e255.gif)
