### ISSUE TITLE
Coordinate System is Incorrect

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/PathWeaver#155]
WPILib's coordinate system (like standard mathematical convention) requires Y-values to increase as you travel upward. This is not the case with Pathweaver, and it will result in the exported trajectories being incorrect.

**Comment by prateekma** [comment]
The bottom left corner should be (0, 0)

**Comment by gftabor** [comment]
I would like to point out that the current system is a standard for images. Upper left pixel is 0,0 extending downwards and rightwards.

It really shouldn't matter at all once you pass these coordinates to a trajectory generator, as they have no concept of global coordinate frames only local ones.

**Comment by prateekma** [comment]
Actually, it does matter. A trajectory that's visualized as turning to the right in PathWeaver will actually cause the robot to turn to the left in real life. This is evidenced by #153.

**Comment by carbotaniuman** [comment]
@prateekma Can you test on latest coord-fix branch? Or if you did say so cause I do not remember.

**Comment by prateekma** [comment]
I will test it once I get back home to the U.S. on Monday.
