### ISSUE TITLE
Should include 2020 field

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/PathWeaver#170]
**Is your feature request related to a problem? Please describe.**  
Pathweaver contains fields for 2018 and 2019, but not 2020

**Describe the solution you'd like**  
Pathweaver should include the 2020 field

**Describe alternatives you've considered**  
Every team creating their own version
Someone creating field files and hosting it outside of a pathweaver release

**Additional context**

**Comment by austindeneau** [comment]
I'm currently working on a simplified field view for the 2020 game in a similar style to the one below from last year.
![2019Board_FRONT_05_web01](https://user-images.githubusercontent.com/8742779/72092380-2d29d200-32e0-11ea-8f43-3c547fbef92a.jpg)

I'm unfamiliar with PathWeaver so if there are specific requirements for the drawings (obviously being proportionally correct is one of them) I can adjust the design to suit.

**Comment by gftabor** [comment]
Closed by #172
