### ISSUE TITLE
Direction arrows flipped horizontally

### ISSUE THREAD

**Issue by babbott1000** [wpilibsuite/PathWeaver#171]
**Describe the bug**  

I've never used PathWeaver before(I've played around with it but I don't remember much) so this might just be something that I'm misinterpreting as a bug, but it seems like unintended behavior to me.  I installed PathWeaver through the main WPILib installer(2020.1.2) and as soon as I opened it up I tried messing around with it and immediately noticed that all direction arrows were mirrored horizontally, including the start point, end point and all way-points in-between.

1. Open PathWeaver
2. Drag direction arrows

**Expected behavior**  

The direction arrows are tangent to the path and parallel to the tangent lines.

**Screenshots**  

![arrows](https://user-images.githubusercontent.com/20113527/72096240-7299cf80-32df-11ea-8f36-b8cf608c4af3.gif)

**Desktop**
 - OS: Windows 10 x64 Version 1903 Build 18362.535
 - Java version: build 1.8.0_231-b11

**Comment by prateekma** [comment]
Solved by #164. Should be in the next release.

**Comment by carbotaniuman** [comment]
This is a known bug and has already been fixed. Nominating to close @gftabor.

**Comment by StealthySemicolon** [comment]
Issue persists in PathWeaver 2020.1.2

**Comment by PeterJohnson** [comment]
It's fixed in 2020.2.2.
