### ISSUE TITLE
Export Units warning not fully displayed

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/PathWeaver#181]
**Describe the bug**  
The warning when opening a project created with an older version of PathWeaver is cut off. This is with PathWeaver from master opening a project created with 2020.2.2.

**To Reproduce**  
1. Open a project created with a previous version of PathWeaver

**Expected behavior**  
All text of warning message should be displayed

**Screenshots**  
![image](https://user-images.githubusercontent.com/4885091/75000552-86267300-5413-11ea-8f28-5bbdc1f3b6a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java version 11.0.1

**Comment by carbotaniuman** [comment]
Can you provide your screen resolution?

**Comment by sciencewhiz** [comment]
1920x1080, 125% text scaling

**Comment by sciencewhiz** [comment]
At 100% text scaling it displays properly

**Comment by jasondaming** [comment]
I added line breaks to this dialog I think this fixes the issue:
![image](https://user-images.githubusercontent.com/15695521/113498768-8679b480-94d5-11eb-8c4f-93ac1e10e9ed.png)
