### ISSUE TITLE
PathWeaver is not building 

### ISSUE THREAD

**Issue by JimWright4089** [wpilibsuite/PathWeaver#183]
Hello all,

Say, the PathWeaver is no longer building.  It feels like I need to set a path to the AllWPILib.

Error messages include:
F:\JimsRobot\PathWeaver\src\main\java\edu\wpi\first\pathweaver\spline\wpilib\WpilibSpline.java:10: error: package edu.wpi.first.wpilibj.kinematics does not exist
import edu.wpi.first.wpilibj.kinematics.DifferentialDriveKinematics;
                                       ^
F:\JimsRobot\PathWeaver\src\main\java\edu\wpi\first\pathweaver\spline\wpilib\WpilibSpline.java:11: error: package edu.wpi.first.wpilibj.spline does not exist
import edu.wpi.first.wpilibj.spline.PoseWithCurvature;
                                   ^
F:\JimsRobot\PathWeaver\src\main\java\edu\wpi\first\pathweaver\spline\wpilib\WpilibSpline.java:12: error: package edu.wpi.first.wpilibj.spline does not exist
import edu.wpi.first.wpilibj.spline.QuinticHermiteSpline;
                                   ^
F:\JimsRobot\PathWeaver\src\main\java\edu\wpi\first\pathweaver\spline\wpilib\WpilibSpline.java:13: error: package edu.wpi.first.wpilibj.spline does not exist
import edu.wpi.first.wpilibj.spline.Spline;
                                   ^
F:\JimsRobot\PathWeaver\src\main\java\edu\wpi\first\pathweaver\spline\wpilib\WpilibSpline.java:14: error: package edu.wpi.first.wpilibj.trajectory does not exist
import edu.wpi.first.wpilibj.trajectory.Trajectory;
                                       ^
**Describe the bug**  
The PAthWeaver does not build or run.

**To Reproduce**  
Download PathWeaver to a clean directory
run 'gradlew run'

**Expected behavior**  
when I type:
gradlew run
I should have the Pathweaver come us.

**Desktop (please complete the following information):**
Windows 10
Ubuntu 18.04 on an Intel PC

**Comment by Kevin-OConnor** [comment]
Pretty sure this is because of wpilibsuite/allwpilib#2629. Seems like some package references need to be updated.

**Comment by JimWright4089** [comment]
Wholly Cats!  You guys are fast.  Thank you very much.
