### ISSUE TITLE
2020 field image is the wrong shape

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/PathWeaver#187]
The 2020 field image bundled with PathWeaver has the wrong aspect ratio, so waypoints drawn with it don't match reality. My team had to add an offset to fix it.

The proper fix is to trim the image to the correct aspect ratio.

**Comment by jasondaming** [comment]
I could not reproduce this issue.  Aspect ratio of the source image should not be needed to give proper measurements.

**Comment by sciencewhiz** [comment]
When I looked at this a while ago, the image is slightly the wrong aspect ratio by about 1%

Looking at the json file 

```
{
    "game" : "Infinite Recharge",
    "field-image" : "2020-Field.png",
    "field-corners": {
        "top-left" : [96, 25],
        "bottom-right" : [1040, 514]
    },
    "field-size" : [52.4375, 26.9375],
    "field-unit" : "foot"
    }
```

bottom-top is 514 - 25 = 489 which corresponds to 26.9375 feet or 18.15
right-left is 1040-96 = 944 which corresponds to 52.4375 feet or 18.00 pixels per foot

The image would need to be stretched by about 1% to fix this.

**Comment by jasondaming** [comment]
I test by putting down a waypoint at a known spot and confirmed the distances were reasonable.  Y was within .25" x was at 1.25" well within the error of putting down the waypoint.
