### ISSUE TITLE
File icon shows up when dragging waypoint

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/PathWeaver#230]
When dragging waypoints around, the file icon is superimposed on top of the triangle. A screenshot is attached below:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/19977330/112649069-7d774c00-8e20-11eb-8fbd-d47cd8fb9c7a.png">

OS: macOS Big Sur (11.2.3)
PathWeaver Version: 2021.2.2

**Comment by jasondaming** [comment]
My guess is that this is a macOS issue.  I have never seen this before.  Is it repeatable (if so what are steps) or does it happen "randomly"?

**Comment by prateekma** [comment]
It always happens when you click and drag on a waypoint. No extra steps are necessary.
