### ISSUE TITLE
Built paths are saved to .../output/ instead of the selected output directory

### ISSUE THREAD

**Issue by BraedenHunt** [wpilibsuite/PathWeaver#234]
**Is your feature request related to a problem? Please describe.**  
PathWeaver creates an "output" folder to place the built paths inside the selected Output Directory.
By selecting the directory ".../deploy/paths/" the user expects that to be where the built paths will be saved, but instead, they are saved to ".../deploy/paths/output/" without the user being able to change that.

**Describe the solution you'd like**  
A checkbox ("Create Output Folder") can be added below or next to the Output Directory selection box on the Edit Project screen. When this box is checked, the current functionality does not change. When it is unchecked, Pathweaver outputs the paths directly into the directory selected without creating an output folder.

**Describe alternatives you've considered**  
Remove the functionality to create a new folder completely. This would have the same functionality as having an unchecked box in the proposed solution.

**Comment by jasondaming** [comment]
If you select the actual root project folder PathWeaver will automatically place in the proper /deploy directory.  If you select a specific directory inside the project pathweaver thinks you need/want to explicitly control where it goes in which case it always uses an output directory.

**Comment by jasondaming** [comment]
Let me know if this solved you issue or if you think there is still room for improvement here!
