### ISSUE TITLE
Cannot open PathWeaver projects due to JPEG library error

### ISSUE THREAD

**Issue by Boomaa23** [wpilibsuite/PathWeaver#246]
**Description**
I cannot open any PathWeaver projects. The welcome screen shows up but when I click on the recent project or try to import/create a new one, nothing happens. Digging into the logs, it appears that the issue lies with the `2019-field.jpg` file not being read by the jpeg library because of this error: `Wrong JPEG library version: library is 80, caller expects 70`.

**Solution**
I changed the `.jpg` images in `src/main/resources/` to `.png` and updated the associated jsons, then ran the project through gradlew. Not an ideal solution and does not address the bug, but it works (see [fork commit here](https://github.com/Boomaa23/PathWeaver/commit/9b3490db423ccd528253fd6ae2456ef7a6ac6c2a)).

**Error log**
Pastebin: https://pastebin.com/z1KwrMuh

**Troubleshooting steps tried**
- Install `libjpeg7` from the AUR
- Set `LD_LIBRARY_PATH` to `/usr/local/lib`
- Install `OpenJFX` separately
- Install the Oracle JDK 11 and switch to it using `archlinux-java`
- Run the jar manually
- Clear `~/PathWeaver/` and `~/wpilib` then reinstall

**Desktop**
 - OS: Arch Linux 2021.04.01
 - Java: OpenJDK v11.0.10 w/ OpenJFX
 - PathWeaver: v2021.2.2

**Comment by prateekma** [comment]
What happens if you launch PathWeaver from VS Code using the "Open Tool" menu (when you click the 3 dots in the upper right-hand corner)? This uses the JDK that we install and is technically the only supported way to launch it.

**Comment by calcmogul** [comment]
It works on my Arch machine. Have you tried libjpeg-turbo?

**Comment by Boomaa23** [comment]
Tried `libjpeg-turbo`, opening via python, and via VS Code. Still same result and error.

**Comment by calcmogul** [comment]
Hm... there must have been a recent ABI update. I can't create new projects in PathWeaver anymore either.

**Comment by calcmogul** [comment]
@Boomaa23 I don't see a `libjpeg7` package in the AUR. How did you install it?

**Comment by Boomaa23** [comment]
@calcmogul I just ran `git clone https://aur.archlinux.org/libjpeg7.git` and installed as usual. I don't use a package manager for AUR and it seemed to build fine. I did try to look for it on the package list and it wasn't there though, not sure what that's about.

**Comment by calcmogul** [comment]
Weird. That package doesn't exist in the search results.

**Comment by calcmogul** [comment]
If I install that libjpeg7 package, running

```bash
LD_PRELOAD=/usr/lib/libjpeg.so.7 ./jdk/bin/jar -jar tools/PathWeaver.jar
```
from `~/wpilib/2021` works. I verified it was loaded by opening the associated maps file for the process's /proc entry and looking for libjpeg.so.7.
```bash
nvim /proc/`pgrep java`/maps
```

Force-loading `./jdk/lib/libjpeg.so` with
```bash
LD_PRELOAD="./jdk/lib/libjpeg.so ./jdk/lib/server/libjvm.so" ./jdk/bin/java -jar tools/PathWeaver.jar
```
failed because it wants libjpeg.so.7 specifically.

**Comment by calcmogul** [comment]
Here's a patched `~/wpilib/2021/tools/PathWeaver.py` that'll set LD_PRELOAD to the right thing on Linux.

[PathWeaver.py.txt](https://github.com/wpilibsuite/PathWeaver/files/6353547/PathWeaver.py.txt)

**Comment by Boomaa23** [comment]
Works perfectly! Thanks @calcmogul.
