### ISSUE TITLE
PathWeaver project configuration:  Wheelbase or Track

### ISSUE THREAD

**Issue by cgzog** [wpilibsuite/PathWeaver#247]
When initially creating a PathWeaver project and entering the various properties, the last field is labeled "Wheel Base".  The documentation at [](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/pathweaver/creating-pathweaver-project.html) describes this as:

> **Wheel Base:** The distance between the left and right wheels of your robot. This is used to ensure that no wheel on a differential drive will go over the specified max velocity around turns.

Coming from the automotive suspension world, this would be referred to as "**Track**" rather than "**Wheel Base**".  Typically Track is measured left-to-right from the center of the tire contact patches while wheel base is measured front-to-rear from the center of the axles.

From the description in the documentation, this would seem to apply to wheel speeds of wheels at different distances from the center of the turn.  While almost every vehicle tire contact patch tracks it's own arc (perfect 4 wheel steering exempted as one example), unless wheel base gets very large compared to track, the wheel speed between front and rear wheels is somewhat small and even in tight turns would be outweighed by the inner and outer wheel speeds for wheels on the same logical axle (things like articulated semi trailers or very long wheel base rigid chassised vehicles would not be applicable here but that's not your typical FRC robot - in that case we're talking vehicles that have wheelbases 3, 4 or even 6 or 7 x their track which would be a very "unusual" FRC robot).

Should this really be re-labeled "Track" in the PathWeaver project properties with the description in the above referenced documentation re-labeled from "Wheel Base" to "Track"?

**Comment by jasondaming** [comment]
Completely agree.  I propose changing it to "Track Width" which is the terminology used by frc-char

**Comment by cgzog** [comment]
That would make it crystal clear.  Thanks.
