### ISSUE TITLE
error MalformedJsonException: Invalid escape sequence at line 3 column 24 path $.field-image

### ISSUE THREAD

**Issue by dorinon** [wpilibsuite/PathWeaver#262]
**Describe the bug**  
im trying to add a new map i followed the instructions and when i run pathwaver it gives me this error and those not open

**To Reproduce**  
1. try to add a map
2. run the program

**Expected behavior**  
opening pathwaver with the addition of the map

**Screenshots**  
my json file:
{
   "game": "testMap",
   "field-image": "C:\Users\User\PathWeaver\Games\customeGame\field-image.png",
      "top-left": [0, 114.3],
      "bottom-right": [236.2, 0]
   },
   "field-size": [236.2, 114.3],
   "field-unit": "cm"
} 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java version [e.g. 11.0.12]

**Additional context**  

its my first time using pathwaver.
the image and the json file are in the same subdirectory

**Comment by PeterJohnson** [comment]
You need to put \\ in place of each \ in the path, since \ is an escape character.

**Comment by jasondaming** [comment]
I assume you were following [these](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/pathweaver/adding-field-images.html) instructions?

As you can see there the line "field-corners": { is needed before top-left.  The json you posted above is not valid, you can tell by the unmatching brackets.

**Comment by jasondaming** [comment]
To @PeterJohnson point I would recommend not including the path and instead just using the filename and placing the file in the game directory

**Comment by jasondaming** [comment]
Do you have any additional questions about this?  If not I will close this issue soon.
