### ISSUE TITLE
Duplicating a path when no path is selected causes NPE

### ISSUE THREAD

**Issue by nickschatz** [wpilibsuite/PathWeaver#66]
**Describe the bug**  
When the duplicate button is pressed when no path is selected, a NullPointerException appears in the console.

Relevant lines of error:
`Caused by: java.lang.NullPointerException
	at edu.wpi.first.pathui.PathDisplayController.flip(PathDisplayController.java:285)
	at edu.wpi.first.pathui.MainController.flipVertical(MainController.java:238)
	... 66 more`

**Comment by gftabor** [comment]
Does the duplicate button also cause the NPE or just flips?

**Comment by nickschatz** [comment]
Er, it was the duplicate at least. I don't recall checking flips, dunno where that title came from.
