### ISSUE TITLE
No delete button when right clicking on point

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/PathWeaver#74]
we should add a delete menu button to the context menu that appears when right clicking a point

**Comment by kjrobrien** [comment]
![image](https://user-images.githubusercontent.com/5257828/43478115-02f59fd2-94cb-11e8-9069-3c4e75ba65b9.png)
Can you clarify what you mean? We currently have right-click delete functionality.

**Comment by AustinShalit** [comment]
Oh... you hide the option when it is not available (I was clicking an end point)... instead of hiding the menu when the option does not exist, can we disable the button with a tooltip that says you cannot delete endpoints?

**Comment by gftabor** [comment]
So this ties into #71 obviously. With the refactoring done in #62 it should be easy to make start and end points deletelable.
