### ISSUE TITLE
Auton with no Paths shows a Path

### ISSUE THREAD

**Issue by kjrobrien** [wpilibsuite/PathWeaver#75]
**Describe the bug**  
When you click on an empty autonomous, an unknown path is shown.
**To Reproduce**  
1. Click on an empty autonomous, such as "Center Auton"

**Expected behavior**  
No path should be shown for an autonomous that is empty.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5257828/43528228-7c0a1956-9576-11e8-9de8-ad1d956ee197.png)

**Comment by kjrobrien** [comment]
The "default" path is then written to the autonomous file, which should not be done. For example 
`X,Y,Tangent X,Tangent Y,Fixed Theta`
`0.0,0.0,10.0,0.0,false`
`10.0,10.0,0.0,10.0,false`
was written to an autonomous file.

**Comment by gftabor** [comment]
The first half I thought I fixed in main controller under autons selection model. It shouldn't tell path display controller to display an auton file.
