### ISSUE TITLE
Autonomous Delete button can delete paths

### ISSUE THREAD

**Issue by kjrobrien** [wpilibsuite/PathWeaver#84]
**Describe the bug**  
Pressing the "-" button underneath the list of Autons will delete the selected Path if no Auton is selected.
**To Reproduce**  
1. Open the program.
2. Select a path from the Paths list.
3. Press the "-" button underneath Autons.

**Expected behavior**  
Nothing should happen as no Auton is selected.

**Comment by gftabor** [comment]
Ya the delete buttons call the same function as the delete /backspace key press. Which deletes whatever is currently selected. It seemed reasonable to just have the behavior across all of them be the same and only have multiple buttons for symmetry.

Obviously additions buttons do different behavior, so it's not necessarily an intuitive system.
