### ISSUE TITLE
Coordinate positions do not match field properly

### ISSUE THREAD

**Issue by kjrobrien** [wpilibsuite/PathWeaver#88]
**Describe the bug**  
The X,Y coordinates do not properly match their locations on the field. For example, a point a 0,0 is not in the corner of the field. (Screenshot below).
**To Reproduce**  
1. Set a waypoint coordinates to 0,0 or 54, 27
2. The points will not be in the expected locations.

**Expected behavior**  
I would expect 0,0 to be one corner of the field and 54,27 to be another corner.

**Screenshots**  
![image](https://user-images.githubusercontent.com/5257828/46214450-39676700-c309-11e8-98e0-6ba9b21ecca3.png)

**Comment by gftabor** [comment]
Can you quickly run through master looking for when this might have happened? I am pretty sure this functioned properly at some point. (0,0) definitely shouldnt start outside of the image.
